version: "3.9"

services:
  database:
    image: postgres
    container_name: tutorial
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ryanb
      - POSTGRES_PASSWORD=8080
      - POSTGRES_DB=crud_fullstack
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local